name: project_environment
channels:
  - defaults
  - conda-forge   # recommended for newer Python/wheel coverage
dependencies:
  - python=3.11
  - pip
  - numpy=1.24.*       # 1.24.x supports Python 3.11.
  - pandas=1.5.*       # pandas 1.5.x officially supports Python 3.11.
  - scikit-learn>=1.5  # newer scikit-learn releases (1.5+) support modern Python; use conda-forge if building from wheels
  - joblib>=1.2
  - matplotlib=3.6.*   # 3.6.x+ is suitable for recent Python
  - seaborn>=0.13      # seaborn supports Python >=3.8 (so OK for 3.11); 0.13+ has bugfixes
  - pillow>=9.3        # Pillow 9.3 added Python 3.11 support
  - pip:
    - 'azureml-defaults>=1.58.0'  # azureml added Python 3.11 support in v1.58.0; pin to >=1.58 if you run on 3.11
